// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoqpcKs7eHD-UxznEMFZrbm53COPBD1Q',
    appId: '1:291022635258:web:2bc1757a8ecc72dd3d8943',
    messagingSenderId: '291022635258',
    projectId: 'inksentinel',
    authDomain: 'inksentinel.firebaseapp.com',
    storageBucket: 'inksentinel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJxtDtWx_6NHng0XuNES6_i0dzJR7KGtg',
    appId: '1:291022635258:android:b2a2503585ffaf103d8943',
    messagingSenderId: '291022635258',
    projectId: 'inksentinel',
    storageBucket: 'inksentinel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDR9qfCFltKDHmbHgZg7uy9vHwwWOQa08',
    appId: '1:291022635258:ios:17765ef6ec7e6ac03d8943',
    messagingSenderId: '291022635258',
    projectId: 'inksentinel',
    storageBucket: 'inksentinel.firebasestorage.app',
    iosBundleId: 'com.example.inksentinel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDR9qfCFltKDHmbHgZg7uy9vHwwWOQa08',
    appId: '1:291022635258:ios:17765ef6ec7e6ac03d8943',
    messagingSenderId: '291022635258',
    projectId: 'inksentinel',
    storageBucket: 'inksentinel.firebasestorage.app',
    iosBundleId: 'com.example.inksentinel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNoqpcKs7eHD-UxznEMFZrbm53COPBD1Q',
    appId: '1:291022635258:web:8e742d28ecf8bd4b3d8943',
    messagingSenderId: '291022635258',
    projectId: 'inksentinel',
    authDomain: 'inksentinel.firebaseapp.com',
    storageBucket: 'inksentinel.firebasestorage.app',
  );

}